version: v1alpha1
machine:
  type: controlplane
  certSANs:
    - "cluster.local"
    - "10.0.0.1"
  kubelet:
    extraArgs:
      rotate-server-certificates: true
  network:
    hostname: talos-cp-1
cluster:
  network:
    cni:
      name: flannel
  controlPlane:
    endpoint: https://10.0.0.1:6443
  clusterName: talos-cluster 